title: CSCI-UA.0480 Spring 2016, Section 010
email: jjv222@nyu.edu

course_number: "CSCI-UA.0480"
course_section: "010"
course_name: "Applied Internet Technology"
course_semester: "Spring 2016"
course_time: "Tuesdays and Thursdays, 11:00AM to 12:15PM"
course_room: WWH 312
course_site: http://foureyes.github.io/csci-ua.0480-spring2016-010/
course_site_alt: http://cs.nyu.edu/~jversoza

# office hours
office_hours: "Mondays and Wednesdays 11:00AM to 12:00PM, Tuesdays 12:30pm to 1:30pm"
office_hours_room: WWH 423

# finals
# CSCI-UA.0480-002  Special Topics: Applied Internet Technology Joseph Versoza      Tuesday, December 16, 2014  8:00AM - 9:50AM 
final_date: TBD
final_time: TBD
final_room: TBD

baseurl: ""
resource_prefix: "resources/"
github_username: jversoza
slides_lib: "../../resources/lib"
slides_img_prefix: "../../resources/img"

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot
permalink: none
exclude: [bower_components, README.md, bower.json, gruntfile.js, node_modules]

book_js: Eloquent JavaScript, 2nd Edition
book_js_note: "(free to read online)"
book_js_link: http://eloquentjavascript.net/
book_js_author: Marijn Haverbeke
book_node: "Node: Up and Running"
book_node_link: http://chimera.labs.oreilly.com/books/1234000001808/index.html
book_node_author: Tom Hughes-Croucher, Mike Wilson
book_web: "Web Dev w/ Node & Express"
book_web_link: http://shop.oreilly.com/product/0636920032977.do
book_web_author: "Ethan Brown"

book_js_2: "Speaking JavaScript"
book_js_2_note: "(free to read online)"
book_js_2_link: http://www.amazon.com/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742  
book_js_2_author: Axel Rauschmayer

